/**
 * Created by HP on 08/28/2021.
 */


export const FETCH_PROPERTY_REQUEST='FETCH_PROPERTY_REQUEST';
export const FETCH_PROPERTY_SUCCESS='FETCH_PROPERTY_SUCCESS';
export const FETCH_PROPERTY_FAILURE='FETCH_PROPERTY_FAILURE';


export const STORE_LOCALPROPERTY='STORE_LOCALPROPERTY';




